CREATE INDEX idx_profilering_profilering_id ON profilering(profilering_id);
CREATE INDEX idx_profilering_periode_id ON profilering(periode_id);
CREATE INDEX idx_profilering_opplysninger_om_arbeidssoeker_id ON profilering(opplysninger_om_arbeidssoeker_id);
CREATE INDEX idx_profilering_sendt_inn_av_id ON profilering(sendt_inn_av_id);